(in-package :cl-user)

(cl:defpackage #:qix
  (:use #:cl)
    (:export
     ;; sdl-wrapper
     #:QIX-WIN
     ;; Buffer
     #:GL-BUFFER
     #:ID
     #:RELEASE-ID #:GET-ID #:BIND #:UN-BIND #:SET-DATA #:MAP-BUFFER #:UNMAP-BUFFER
     #:SET-VERTEX-POINTER #:SET-NORMAL-POINTER #:SET-COLOR-POINTER #:SET-SECONDARY-COLOR-POINTER
     #:SET-EDGE-POINTER #:SET-TEX-POINTER #:SET-FOG-COORDINATE-POINTER #:WITH-MAPPED-BUFFER

     #:GL-MESH
     #:RENDER #:RELEASE-BUFFERS

     #:TEXTURE
     #:GET-ID #:BIND #:RELEASE-TEXTURE #:INITIALIZE-INSTANCE #:LOAD-2D-IMAGE

     #:GL-MATERIAL
     #:INITIALIZE-INSTANCE #:SET-AMBIENT #:UNSET-AMBIENT #:GET-AMBIENT
     #:SET-DIFFUSE #:UNSET-DIFFUSE #:GET-DIFFUSE #:SET-SPECULAR #:UNSET-SPECULAR #:GET-SPECULAR
     #:SET-EMISSION #:UNSET-EMISSION #:GET-EMISSION #:USE #:GET-CURRENT-MATERIAL-PROPERTY

     #:GL-LIGHT
     #:*LIGHTS* #:*GLOBAL-AMBIENT-LIGHT* #:*LIGHT0* #:LIGHTS-RESET #:LIGHTS-INIT
     #:SET-GLOBAL-AMBIENT-LIGHT #:GET-ENABLED-LIGHTS #:INITIALIZE-INSTANCE
     #:RELEASE-LIGHT #:GET-ID #:SET-LOCATION #:GET-LOCATION #:SET-AMBIENT #:GET-AMBIENT
     #:SET-DIFFUSE #:GET-DIFFUSE #:SET-SPECULAR #:GET-SPECULAR #:SET-CONSTANT-ATTENUATION
     #:SET-LINEAR-ATTENUATION #:SET-QUADRATIC-ATTENUATION

     #:MOVER
     #:INITIALIZE-INSTANCE #:START-MOVER #:GET-CURRENT-VALUE

     #:RAD->DEG #:DEG->RAD
     #:LAW-OF-COSINES #:TRANSPOSE #:CROSS-PRODUCT #:NORMALIZE-VECTOR
     #:GET-LENGTH #:MAKE-IDENTITY-MATRIX #:MAKE-TRANSLATION-MATRIX
     #:MAKE-ROTATION-MATRIX #:MAKE-SCALING-MATRIX #:BILLBOARD-M #:BILLBOARD-POS
     #:MAKE-RANDOM-MATRIX #:ADDMM #:ADDVV #:MULTVV #:MULTMV #:MULTMM

     #:TEXT-VIEW
     #:DATA #:CAIRO-SURFACE #:CAIRO-CONTEXT #:PANGO-CONTEXT #:PANGO-LAYOUT 
     #:MARKUP #:HEIGHT #:WIDTH #:STORAGE-TYPE #:WORD-WRAP #:TEXT-FONT
     #:PAGE-X #:PAGE-Y #:TEXT-WIDTH #:TEXT-COLOR #:TEXT-WIDTH #:TEXT-COLOR #:BACKGROUND-COLOR

     #:INITIALIZE-CAIRO-SURFACE #:RELEASE-CAIRO-SURFACE
     #:INITIALIZE-CAIRO-CONTEXT #:RELEASE-CAIRO-CONTEXT #:GET-CAIRO-CONTEXT-POINTER
     #:INITIALIZE-PANGO-CONTEXT #:RELEASE-PANGO-CONTEXT #:INITIALIZE-PANGO-LAYOUT
     #:RELEASE-PANGO-LAYOUT #:IMAGE-SURFACE-DATA 

     #:DRAW-TEXT #:WRITE-TO-PNG
     ))